### ISSUE TITLE
Visualizer from ConductR Master does not load due to roles

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/sbt-conductr-sandbox#37]
The Visualizer sample application built out of ConductR Master does not run in current sandbox.

``` bash
[visualizer] $ conduct load file:/home/edc/src/edc/typesafe-conductr/visualizer/target/bundle/visualizer-v1.1-d94eb5c3be3417f0f37128f9adf1bafe1d1b5e16a6215949a1b34249f03930ad.zip
[info] Loading bundle to ConductR ...
[trace] Stack trace suppressed: run last visualizer/*:conduct for the full output.
[error] (visualizer/*:conduct) Problem loading the bundle: No offers received. Ensure suitable member availabilty.
[error] Ask timed out on [Actor[akka://conductr/user/reaper/load-scheduler#454674482]] after [60000 ms]
[error] Total time: 61 s, completed Oct 15, 2015 2:53:10 PM
```

**Comment by huntc** [comment]
@edwardcallahan I'm unsure about the roles issue here - I see the log of course, but I'm unable to reproduce. Can you please try again given a release of the sandbox following https://github.com/typesafehub/sbt-conductr-sandbox/pull/40 ?

**Comment by markusjura** [comment]
Tested it as well. For me the visualizer loads successfully on the current conductr master branch and the latest sbt plugins.
