### ISSUE TITLE
Make port mappings a little easier to understand

### ISSUE THREAD

**Issue by huntc** [typesafehub/sbt-conductr-sandbox#39]
Instead of port 9999 becoming 9909, 9919 and 9929 for a 3 node cluster, let them become 9999, 9919 and 9929 i.e. retain the first port as the user might expect it.

**Comment by huntc** [comment]
@rocketpages?

**Comment by markusjura** [comment]
Yes, we can do that. Also we should change the port mapping documentation to describe the example based on one node. So far our docker image only supports a single node. Therefor this documentation in the README.md is confusing.

Create this issue accordingly: https://github.com/typesafehub/sbt-conductr-sandbox/issues/41

**Comment by markusjura** [comment]
How should we deal with this scenario:
- Port is 9010
- 3 ConductR nodes

If we 9010 becomes 9010 for the first node then what should be the ports for the second and third node? What we could do is that we always increase the value. So in the above scenario the ports would become 9010, 9020, 9030.

Would this implementation be intuitive than the currently?

**Comment by markusjura** [comment]
Implementation has changes as stated in the previous comment.

**Comment by markusjura** [comment]
Corresponding PR is https://github.com/typesafehub/sbt-conductr-sandbox/pull/60.
