### ISSUE TITLE
Automatically stop docker container at startup

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr-sandbox#42]
If an docker container has been already started the sandbox `run` command returns this error:

```
[info] Running container cond-0 exposing 192.168.59.103:9000, 192.168.59.103:1101...
[error] Error response from daemon: Conflict. The name "cond-0" is already in use by container cd9bdec12793. You have to delete (or rename) that container to be able to reuse that name.
```

Now the user need to manually remove the container with:

```
docker rm cond-0
```

Should we instead remove this docker container automatically during `sandbox run` in case it already exists?

@huntc: WDYT?

**Comment by huntc** [comment]
Yeah, it isn't good that it is reported as an error - it isn't really an error. We should perhaps test whether it already exists and inform the user that we're not starting one in its place. It is useful to have the script skip over ones that already exist so that you can add a node during demos.

**Comment by markusjura** [comment]
The solution we are implementing is the following (after consulting with @huntc):
- The error message are turned into an info message
- The `sandbox run` command is becoming a new option `--nrOfContainers`. With this option the user can dynamically remove or add cluster nodes. The sbt settings key `nrOfContainers` will be removed instead. The new logic is aligned with the `conduct run` command.

**Comment by markusjura** [comment]
Addressed with PR https://github.com/typesafehub/sbt-conductr-sandbox/pull/53.
