### ISSUE TITLE
sbt-conductr-sandbox enables sbt-conductr plugin

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr-sandbox#49]
It seems that the `sbt-conductr-sandbox` plugin enables the `sbt-conductr` plugin automatically.

**Test**
1. Use current version of `conductr-service-lookup` as a test project
   
   ```
   git clone git@github.com:typesafehub/conductr-service-lookup.git
   ```
2. Remove `sbt-conductr` plugin in the `plugins.sbt`
3. Start sbt session. Output:
   
   ```
   [info] Set current project to conductR-service-lookup (in build file:/Users/mj/workspace/conductr-service-lookup/)
   [info] Control Protocol set for http://192.168.99.100:9005. Use `controlServer` to set an alternate address.
   >
   ```

The `controlServer` command is executing during sbt session startup. The `controlServer` command is part of `sbt-conductr`. Also in the sbt session it is now possible to use all `sbt-conductr` related commands such as `conduct info`, etc.

If this assumption is correct we could simply `sbt-conductr-sandbox` such that we don't need to check if certain `ConductRPlugin` keys are set or not.

@huntc: WDYT?

**Comment by huntc** [comment]
Sbt-conductr shouldn't be a requirement and thus enabled... It'd be useful to know if it is enabled. I didn't think it was...

**Comment by markusjura** [comment]
sbt-conductr gets enabled automatically (test is proving it). So far we used only the `ConductRKeys.conductrControlServerUrl` directly without checking if the key exists. I was mixed it up with `BundleKeys`. So for `sbt-conductr-sandbox` no code change is necessary. However, we should update our documentation on conductr.typesafe.com and the README.mds accordingly so that only the sbt plugin `sbt-conductr-sandbox` need to be added to the `plugins.sbt`, not both.

**Comment by huntc** [comment]
I'd forgotten about setting that key. In that case a requires statement is in order.

**Comment by markusjura** [comment]
So should `sbt-conductr` be automatically enabled if `sbt-conductr-sandbox` is added to the `plugins.sbt`?

So far we do not override the `requires` method in `sbt-conductr-sandbox`, only the `trigger` method:

```
override def trigger = allRequirements
```

However, if I add `sbt-conductr-sandbox` without `sbt-conductr` then I can use the `conduct` command as well, without enabling any addtional plugin, e.g.

lazy val ferryService = (project in file("akka-back"))
  .settings(
    version := "0.1.0-SNAPSHOT",
    scalaVersion := "2.11.7"
    name := "ferry-boat",
    description := "River Boat Transport Services, LLC",
    BundleKeys.nrOfCpus := 1.0,
    BundleKeys.memory := 64.MiB,
    BundleKeys.diskSpace := 15.MB,
    BundleKeys.roles  := Set("backend"),
    BundleKeys.endpoints := Map(
      "ferry" -> Endpoint("http", services = Set(URI("http://:9666/ferry")))),
    libraryDependencies ++= Dependencies.conductrAkkaScala,
    fork in run := true
  )

Is this the expected behavior? If so we need to change our documentation accordingly so that we only add `sbt-conductr-sandbox` and not `sbt-conductr` to the `plugins.sbt` in case the sandbox plugin is used.

**Comment by markusjura** [comment]
**PRs**
sbt-conductr-sandbox: https://github.com/typesafehub/sbt-conductr-sandbox/pull/52
conductr: https://github.com/typesafehub/conductr/pull/907
conductr-doc: https://github.com/typesafehub/conductr-doc/pull/105
conductr-service-lookup: https://github.com/typesafehub/conductr-service-lookup/pull/3
