### ISSUE TITLE
controlServer is hosed

### ISSUE THREAD

**Issue by huntc** [typesafehub/sbt-conductr-sandbox#61]
I think that we may have recently introduced a bug where the controlServer is no longer assigned. I recall that we changed this to use a task. Unfortunately that doesn't work for some reason.

I simply started the sandbox from within the conductr module and attempted `conduct info`. No joy.

**Comment by markusjura** [comment]
For me it is working fine:

```
$ ~/workspace/sbt-conductr-sandbox/sbt-conductr-sandbox-tester$ sbt
[info] Loading global plugins from /Users/mj/.sbt/0.13/plugins
[info] Loading project definition from /Users/mj/workspace/sbt-conductr-sandbox/project
[info] Loading project definition from /Users/mj/workspace/sbt-conductr-sandbox/sbt-conductr-sandbox-tester/project
[info] Set current project to simple-test (in build file:/Users/mj/workspace/sbt-conductr-sandbox/sbt-conductr-sandbox-tester/)
[info] Control Protocol set for http://192.168.99.100:9005. Use `controlServer` to set an alternate address.
> sandbox run
[info] Starting ConductR nodes..
[info] Starting container cond-0 exposing 192.168.99.100:9000, 192.168.99.100:9999...
[info] 6a4346d7541c65e442980fdfdcd21587b3e5bafe946fc6fb52fe91c8a7671a12
[info] Set current project to simple-test (in build file:/Users/mj/workspace/sbt-conductr-sandbox/sbt-conductr-sandbox-tester/)
[info] Control Protocol set for http://192.168.99.100:9005. Use `controlServer` to set an alternate address.
> conduct info
ID                         NAME                            #REP   #STR   #RUN

[success] Total time: 1 s, completed Oct 31, 2015 9:26:34 AM
```
- control server is set to the correct address http://192.168.99.100:9005
- `sandbox run` starts cond-0
- `conduct info` displays the running containers (none in this case)

Can you try it with the same `sbt-conductr-sandbox-tester` project inside `sbt-conductr-sandbox`? Can you also send the error output for this. Maybe it has something todo that I am using `docker-machine` and you `boot2docker`?

**Comment by huntc** [comment]
Perhaps it is a multi module thing. I tested within the ConductR project. I'll try again though.

**Comment by huntc** [comment]
The latest changes to the sandbox plugin had not been published. I've now created a 1.2.0 release given the API change to `runConductRs`. The ConductR project is updated with https://github.com/typesafehub/conductr/pull/922

**Comment by huntc** [comment]
I also test from a multi-module project and all appears to be well.

**Comment by huntc** [comment]
@markusjura Are there documentation changes to go with the changes introduced by 1.2.0 - particularly the port mappings - would you mind?

**Comment by markusjura** [comment]
The current port mapping documentation in the README.md of sbt-conductr-sandbox has been changed with this PR: https://github.com/typesafehub/sbt-conductr-sandbox/pull/60

The change regarding `--nr-of-containers` has been updated both in the README.md as well as on conductr.typesafe.com.

There are no additional things to document.

**Comment by huntc** [comment]
Nice work @markusjura
