### ISSUE TITLE
This repo shouldn't be a fork

### ISSUE THREAD

**Issue by dotta** [typesafehub/sbt-conductr-sandbox#75]
The fact that this repo is a fork of https://github.com/huntc/sbt-conductr-sandbox is wrong, it should be other way around.

**Comment by huntc** [comment]
Well, the fact is that it is a fork of my original repo. :-)

How does one amend this?

**Comment by dotta** [comment]
Don't know how to amend it. You should have probably transfer ownership of your repo to typesafehub, instead of forking. Maybe try to reach out to GitHub to see what are your options.

**Comment by huntc** [comment]
We're going to merge this repo with sbt-conductr anyhow, so I won't bother if that's ok. Closing for now.

**Comment by dotta** [comment]
ok
